/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import React from "react";
import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import Project from "../components/project/Project";

type Props = {
  posts: any;
};

const Home = (props: Props) => {
  const postList = props.posts.map((post: any) => {
    //extract slug and frontmatter
    const { slug, frontmatter } = post;

    //JSX for individual blog listing
    return <Project key={slug} project={frontmatter} slug={slug} />;
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <section>
          <div>
            <div className="highlight">
              <div className="main">Fullstack developer</div>
            </div>
            <p>
              Programátor, Kodér, UI/UX designer samouk, Tech lover a nadšenec
              do Automatizace a IOT. Zajímám se o novinky v oblasti vývoje webů.
            </p>
          </div>
          <div className="scroll-downs">
            <div className="mousey">
              <div className="scroller"></div>
            </div>
          </div>
        </section>
        <section id="projects">
          <div className="projects">
            <h1>Projekty</h1>
            {postList}
          </div>
        </section>
        <section id="about">
          <div>
            <h1>About</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Pellentesque euismod, nisi eu consectetur consectetur, nisl nisl
              consectetur nisl, eu consectetur nisl nisl euismod nisl.
            </p>
          </div>
        </section>
        <section>
          <div>
            <h1>Contact</h1>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              Pellentesque euismod, nisi eu consectetur consectetur, nisl nisl
              consectetur nisl, eu consectetur nisl nisl euismod nisl.
            </p>
          </div>
        </section>
      </>
    </>
  );
};

//Generating the Static Props for the Blog Page
export async function getStaticProps() {
  // get list of files from the posts folder
  const files = fs.readdirSync("posts");

  // Sort files by

  // get frontmatter & slug from each post
  const posts = files.map((fileName) => {
    const slug = fileName.replace(".md", "");
    const readFile = fs.readFileSync(`posts/${fileName}`, "utf-8");
    const { data: frontmatter } = matter(readFile);

    return {
      slug,
      frontmatter,
    };
  });

  // Return the pages static props
  return {
    props: {
      posts,
    },
  };
}

export default Home;
